frontends:
  - id: gcode_printer3d
    label: GCode 3D Printer
  - id: gcode_cnc
    label: GCode CNC

backends:
  - id: kuka_krl
    label: KUKA KRL
    robots:
      - id: kuka_krl_kr640
        label: KR 640 R2800-2
      - id: kuka_krl_kr4r600
        label: KR 4 R600
  - id: urscript
    label: URScript
  - id: pseudo_robot_3d
    label: Pseudo Robot 3D
  - id: debug
    label: Debug
