/* ============================================================================
 *  dummy_engine.cpp  —  Atrapa silnika MotionBridge
 *
 *  Implementuje runTranslationFromYaml zgodnie z kontraktem:
 *    - czyta motionbridge_run.yaml (minimalne parsowanie)
 *    - pisze progress_file (START / PROGRESS / DONE) z fflush po każdej linii
 *    - sprawdza cancel.flag między krokami
 *    - pisze dummy SRC/DAT + motionbridge_result.yaml
 *    - zwraca 0=OK, 2=FAILED
 * ==========================================================================*/
#include <chrono>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <optional>
#include <sstream>
#include <string>
#include <thread>

namespace fs = std::filesystem;

/* --------------------------------------------------------------------------
 *  Minimal YAML field extractor — szuka pierwszego wystąpienia "key: value"
 *  lub "key: \"value\"". Wystarczy dla prostego run.yaml.
 * --------------------------------------------------------------------------*/
static std::string yamlField(const std::string& src, const std::string& key)
{
    std::string pat = key + ":";
    auto pos = src.find(pat);
    if (pos == std::string::npos) return {};
    pos += pat.size();

    /* Pomiń spacje/taby po dwukropku — GUI wyrównuje wartości wieloma spacjami. */
    while (pos < src.size() && (src[pos] == ' ' || src[pos] == '\t')) ++pos;
    if (pos >= src.size()) return {};

    if (src[pos] == '"') {
        ++pos;
        auto end = src.find('"', pos);
        if (end == std::string::npos) return {};
        return src.substr(pos, end - pos);
    }
    auto end = src.find_first_of("\r\n", pos);
    std::string val = src.substr(pos, end == std::string::npos ? std::string::npos : end - pos);
    while (!val.empty() && (val.back() == ' ' || val.back() == '\t')) val.pop_back();
    return val;
}

/* --------------------------------------------------------------------------
 *  ProgressReporter — dopisuje linie do pliku progresu z natychmiastowym flush
 * --------------------------------------------------------------------------*/
class ProgressReporter {
public:
    explicit ProgressReporter(std::optional<fs::path> path)
    {
        if (path)
            out_ = std::fopen(path->string().c_str(), "a");
    }
    ~ProgressReporter() { if (out_) std::fclose(out_); }

    void start() { write("START\n"); }

    void progress(int percent, const char* stage)
    {
        char buf[256];
        std::snprintf(buf, sizeof(buf), "PROGRESS %d %s\n", percent, stage);
        write(buf);
    }

    void done(int code)
    {
        char buf[32];
        std::snprintf(buf, sizeof(buf), "DONE %d\n", code);
        write(buf);
    }

private:
    FILE* out_ = nullptr;
    void write(const char* line) {
        if (!out_) return;
        std::fputs(line, out_);
        std::fflush(out_);
    }
};

/* --------------------------------------------------------------------------
 *  Symulacja pracy silnika
 * --------------------------------------------------------------------------*/
static int simulate(const std::string& outputDir,
                    const std::string& gcodeFile,
                    const std::string& resultFile,
                    ProgressReporter& pr)
{
    auto cancelFlag = fs::path(outputDir) / "cancel.flag";

    struct Step { int pct; const char* stage; int ms; };
    static const Step steps[] = {
        {  5, "parsing",                  300 },
        { 20, "parsing G-code",           400 },
        { 35, "validating",               300 },
        { 50, "lowering",                 500 },
        { 65, "lowering poses",           400 },
        { 80, "emitting KRL",             350 },
        { 95, "writing output files",     200 },
        {100, "done",                       0 },
    };

    for (auto& s : steps) {
        if (fs::exists(cancelFlag)) {
            pr.done(3);
            return 3;
        }
        std::this_thread::sleep_for(std::chrono::milliseconds(s.ms));
        pr.progress(s.pct, s.stage);
    }

    /* Dummy SRC */
    std::string srcPath = outputDir + "/program.src";
    if (auto f = std::ofstream(srcPath)) {
        f << "DEF program()\n"
          << ";  Generated by MotionBridge DUMMY engine\n"
          << ";  Input: " << gcodeFile << "\n"
          << "INI\n"
          << "  SPTP HOME Vel=100% DEFAULT\n"
          << "  SLIN P1 Vel=0.2 m/s CPDAT1 Tool[1] Base[1]\n"
          << "  SLIN P2 Vel=0.2 m/s CPDAT2 Tool[1] Base[1]\n"
          << "  SPTP HOME Vel=100% DEFAULT\n"
          << "END\n";
    }

    /* Dummy DAT */
    std::string datPath = outputDir + "/program.dat";
    if (auto f = std::ofstream(datPath)) {
        f << "DEFDAT program\n"
          << "  DECL E6POS XP1={X 900.0,Y 0.0,Z 800.0,A 0.0,B 0.0,C 0.0,"
             "S 6,T 27,E1 0.0,E2 0.0,E3 0.0,E4 0.0,E5 0.0,E6 0.0}\n"
          << "  DECL E6POS XP2={X 950.0,Y 0.0,Z 800.0,A 0.0,B 0.0,C 0.0,"
             "S 6,T 27,E1 0.0,E2 0.0,E3 0.0,E4 0.0,E5 0.0,E6 0.0}\n"
          << "ENDDAT\n";
    }

    /* Dummy errors/warnings/infos logs */
    std::string errPath  = outputDir + "/errors.log";
    std::string warnPath = outputDir + "/warnings.log";
    std::string infoPath = outputDir + "/infos.log";
    { std::ofstream f(errPath); }  /* pusty */
    if (auto f = std::ofstream(warnPath))
        f << "W001: dummy backend — no real kinematics performed\n";
    if (auto f = std::ofstream(infoPath))
        f << "I001: translation simulation completed\n";

    /* motionbridge_result.yaml */
    std::string resultPath = outputDir + "/" + resultFile;
    if (auto f = std::ofstream(resultPath)) {
        f << "status:\n"
          << "  success: true\n"
          << "  code: 0\n"
          << "  message: \"Translation completed successfully.\"\n"
          << "files:\n"
          << "  src:      \"" << srcPath  << "\"\n"
          << "  dat:      \"" << datPath  << "\"\n"
          << "  errors:   \"" << errPath  << "\"\n"
          << "  warnings: \"" << warnPath << "\"\n"
          << "  infos:    \"" << infoPath << "\"\n";
    }

    return 0;
}

/* --------------------------------------------------------------------------
 *  Główna funkcja eksportowana — jedyna publiczna granica
 * --------------------------------------------------------------------------*/
extern "C" int runTranslationFromYaml(char const* yaml_path) noexcept
{
    try {
        std::ifstream ifs(yaml_path);
        if (!ifs) return 2;
        std::string content((std::istreambuf_iterator<char>(ifs)),
                             std::istreambuf_iterator<char>());

        std::string outputDir   = yamlField(content, "dir");
        std::string resultFile  = yamlField(content, "result_file");
        std::string progressFile = yamlField(content, "progress_file");
        std::string gcodeFile   = yamlField(content, "gcode");

        if (outputDir.empty())  outputDir  = ".";
        if (resultFile.empty()) resultFile = "motionbridge_result.yaml";

        fs::create_directories(fs::path(outputDir));

        std::optional<fs::path> progressPath;
        if (!progressFile.empty())
            progressPath = fs::path(progressFile);

        ProgressReporter pr(progressPath);
        pr.start();

        int rc = simulate(outputDir, gcodeFile, resultFile, pr);
        pr.done(rc);
        return rc;
    }
    catch (...) { return 2; }
}
